
package com.chenzhou.bos.service.action.base.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.chenzhou.bos.bean.take_delivery.Order;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://base.action.service.bos.chenzhou.com/")
@XmlSeeAlso({
})
public interface OrderService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://base.action.service.bos.chenzhou.com/", className = "com.chenzhou.bos.service.action.base.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://base.action.service.bos.chenzhou.com/", className = "com.chenzhou.bos.service.action.base.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
